version: '3.1'

services:
  database:
    image: mongo:8.0.3
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-log:/var/log/mongodb

volumes:
  mongo-data:
  mongo-log:
