services:
  database:
    container_name: impostor-database
    image: mongo:8.0.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-log:/var/log/mongodb
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  api:
    container_name: impostor-api
    build:
      context: apps
      dockerfile: api/Dockerfile
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_URL: "mongodb://impostor-database:27017"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8000/iamalive || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  application_initializer:
    container_name: impostor-application-initializer
    depends_on:
      database:
        condition: service_healthy      
    build:
      context: apps
      dockerfile: application_initializer/Dockerfile
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_URL: "mongodb://impostor-database:27017"
    volumes:
      - apps:/app/application_initializer

  inference_model:
    container_name: impostor-inference-model
    depends_on:
      application_initializer:
        condition: service_completed_successfully
    build:
      context: apps
      dockerfile: inference_model/Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - apps:/app/inference_model
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8000/iamalive || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  web:
    container_name: impostor-web
    build: 
      context: apps
      dockerfile: web/Dockerfile
    ports:
      - "80:5173"
    depends_on:
      api:
        condition: service_healthy    
volumes:
  mongo-data:
  mongo-log:
  apps:
