services:
  database:
    container_name: impostor-database
    image: mongo:8.0.3
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-log:/var/log/mongodb
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  api:
    container_name: impostor-api
    build:
      context: apps
      dockerfile: api/Dockerfile
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_URL: "mongodb://impostor-database:27017"
    ports:
      - "8000:8000"
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8000/iamalive || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  mongo-data:
  mongo-log:
