services:
  api:
    container_name: impostor-api
    build:
      context: apps
      dockerfile: api/Dockerfile
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_URL: "mongodb://impostor-database:27017"
    ports:
      - "8000:8000"
