name: PyLint
on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic pylint
      - name: Check linting with PyLint
        run: |
          pylint apps/db_connector/src
          pylint apps/api/src

